version: "3"
services:
  site:
    command: bash -c "gem install bundler && bundle update && jekyll serve --watch --incremental"
    image: jekyll/jekyll:latest
    ports:
        - 4000:4000
    volumes:
        - $PWD:/srv/jekyll